# Generated by Django 5.1.7 on 2025-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.TimeField(auto_created=True)),
                ('url', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=255)),
                ('updatedAt', models.TimeField(auto_now_add=True)),
                ('accessCount', models.IntegerField()),
            ],
        ),
    ]
