# Generated by Django 5.1.7 on 2025-03-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Shortening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='accessCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='createdAt',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='updatedAt',
            field=models.TimeField(auto_now=True),
        ),
    ]
