# Generated by Django 5.1.7 on 2025-03-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Shortening', '0002_alter_url_accesscount_alter_url_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
